/**
 * Machinist Mario Engine — Asset Factory
 *
 * Defines the BaseMachinistAsset interface and the AssetFactory registry that
 * all machining modules must implement. Every asset produces:
 *   • A set of Vector3 toolpaths
 *   • An AABB safety envelope
 *   • G-Code output for a 3-axis CNC machine or 3D printer
 *
 * Also contains the AssetPremium class (Cart 03) that links geometry to the
 * Infinity Crown Index value-logic.
 */
import { Vector3 } from './vector3';
import { AABB } from './kinematics';

// ── Core interface ────────────────────────────────────────────────────────────

/**
 * Every machining module must implement this interface.
 * The generic parameter `TParams` lets each asset declare its own
 * configuration object without losing type safety.
 */
export interface BaseMachinistAsset<TParams = Record<string, number>> {
  /** Human-readable name, e.g. "Aero-Turbine Blade". */
  readonly name: string;

  /** Asset category tag, e.g. "aerospace" | "medical" | "musical". */
  readonly category: string;

  /** Configurable parameters (dimensions, counts, pitches, …). */
  params: TParams;

  /**
   * Build and return the ordered toolpath as Vector3 waypoints.
   * Called before `toGCode()`.
   */
  buildToolpath(): Vector3[];

  /**
   * Compute the axis-aligned bounding box that encloses all toolpath points.
   * Used by the IK safety system to prevent out-of-bounds motion.
   */
  computeAABB(): AABB;

  /**
   * Render the full G-Code program as a string.
   * Must include a preamble (units, absolute mode) and a safe park move.
   */
  toGCode(): string;
}

// ── G-Code helpers ────────────────────────────────────────────────────────────

/** Standard G-Code preamble: metric units, absolute mode, home spindle. */
export function gcodePreamble(assetName: string): string {
  return [
    `; === Machinist Mario — ${assetName} ===`,
    `; Generated by the Modular Asset Factory`,
    `G21       ; Metric units (mm)`,
    `G90       ; Absolute positioning`,
    `G28       ; Auto-home all axes`,
    `M104 S200 ; Set extruder temperature (200°C)`,
    `M140 S60  ; Set bed temperature (60°C)`,
    `M109 S200 ; Wait for extruder temperature`,
    `M190 S60  ; Wait for bed temperature`,
    `G92 E0    ; Reset extruder`,
    `G1 Z5 F5000 ; Lift nozzle`,
    ``,
  ].join('\n');
}

/** Standard G-Code epilogue: retract, lift, fan off, motors off. */
export function gcodeEpilogue(): string {
  return [
    ``,
    `; === End of print ===`,
    `G1 E-3 F1800   ; Retract filament`,
    `G1 Z+10 F5000  ; Lift nozzle`,
    `G28 X0 Y0      ; Park head`,
    `M106 S0        ; Fan off`,
    `M84            ; Disable motors`,
  ].join('\n');
}

/**
 * Converts an ordered array of Vector3 waypoints into G1 feed-rate moves.
 * The first move uses a slower approach feed; subsequent moves use `feedRate`.
 */
export function toolpathToGCode(
  points: Vector3[],
  feedRate: number = 1500,
  extrusionPerMm: number = 0.033,
): string {
  if (points.length === 0) return '';

  const lines: string[] = [];
  let extrusion = 0;

  lines.push(`G1 ${points[0].toGCode(3)} F${feedRate * 0.5} ; approach`);

  for (let i = 1; i < points.length; i++) {
    const seg = points[i].distanceTo(points[i - 1]);
    extrusion += seg * extrusionPerMm;
    lines.push(`G1 ${points[i].toGCode(3)} E${extrusion.toFixed(5)} F${feedRate}`);
  }

  return lines.join('\n');
}

// ── AssetPremium (Cart 03) ────────────────────────────────────────────────────

/**
 * Cart 03 — Asset Premium Logic.
 * Links the Infinity Crown Index to 3D geometry by applying market-driven
 * scale transforms to toolpath points.
 */
export class AssetPremium {
  /**
   * Apply Crown Index physics to a geometry array.
   * For known premium assets the geometry is scaled by the corresponding
   * growth factor; all other assets are returned unmodified.
   */
  static applyMarketPhysics(asset: string, geometry: Vector3[]): Vector3[] {
    const scale = AssetPremium.GROWTH_FACTORS[asset];
    if (scale !== undefined) {
      return geometry.map(p => p.scale(scale));
    }
    return geometry;
  }

  /** Registered growth factors keyed by asset identifier. */
  static readonly GROWTH_FACTORS: Readonly<Record<string, number>> = {
    '1892_DIME':           1.17,
    'IOWA_SILVER_RECOVERY': 1.09,
    'SILVER_SCARCITY':      1.05,
  };
}

// ── AssetFactory registry ─────────────────────────────────────────────────────

type AssetConstructor = new () => BaseMachinistAsset;

/**
 * Central registry for all machining asset modules.
 * Modules register themselves by calling `AssetFactory.register()` at import time.
 */
export class AssetFactory {
  private static readonly _registry = new Map<string, AssetConstructor>();

  /** Register a new asset class under a unique key. */
  static register(key: string, ctor: AssetConstructor): void {
    if (AssetFactory._registry.has(key)) {
      throw new Error(`AssetFactory: duplicate key "${key}"`);
    }
    AssetFactory._registry.set(key, ctor);
  }

  /** Instantiate a registered asset by key. */
  static create(key: string): BaseMachinistAsset {
    const Ctor = AssetFactory._registry.get(key);
    if (!Ctor) throw new Error(`AssetFactory: unknown asset "${key}"`);
    return new Ctor();
  }

  /** Returns all registered asset keys. */
  static keys(): string[] {
    return [...AssetFactory._registry.keys()];
  }
}
